# Generated by Django 5.0.1 on 2024-10-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.TextField(default='First Post', max_length=20),
            preserve_default=False,
        ),
    ]
